### ISSUE TITLE
Cannot set application disk quota through CLI

### ISSUE THREAD

**Issue by trastle** [cloudfoundry/cli#102]
It is not possible to set an application's disk quota from the CLI using a CF push. However it is possible to do this via the CF API and the `manifest.yml` this is not consistent. 

We have some users who need to set the disk quota, explaining to them how to use `cf curl` is pretty rough. It is possible to add this to the CLI?
#### Notes

It is possible to set the disk quota for an application using the application's `manifest.yml`.
The required property is disk_quota:

```

---
applications:
- name: testapp-large-disk
  memory: 512M
  instances: 1
  disk_quota: 3072
  path: .
```
##### Setting the disk quota manually

There is currently no CLI command to set the disk quota for an app, however it is supported by the Cloud Foundry REST API. This means you can set the disk quota using the `cf curl` command.

```
$ cf curl /v2/apps

# Find the metadata.guid for the app you want to increase the disk quota of

$ cf curl /v2/apps/[APP-GUID-HERE] -X PUT -d '{"disk_quota":2048}'
```
