### ISSUE TITLE
YAML Anchors not working in 6.37.0 version

### ISSUE THREAD

**Issue by torrespro** [cloudfoundry/cli#1405]
## Command

cf push -f manifest.yml

## What occurred

YAML Anchors are being ignored when we push the following manifest:

```
---
# SHARED CONFIGURATION
defaults: &defaults
  instances: 1
  memory: 1GB
  disk_quota: 300M
  health-check-type: http
  health-check-http-endpoint: /health
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  env:
    eureka.client.serviceUrl.defaultZone: https://registry-cx-editorial.apps.backbasepcf.com/eureka
    EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
    EUREKA_INSTANCE_HOSTNAME: $CF_INSTANCE_INTERNAL_IP
    EUREKA_INSTANCE_NON_SECURE_PORT: 8080
    SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
    EXTERNAL_SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
    EXTERNAL_ENC_SECRET_KEY: JWTEncKeyDontUseInProduction666!
    LOGGING_SECURED_ENABLED: false
    JBP_CONFIG_DEBUG: '{enabled: true}'
    BACKBASE_ENVROLE: editorial

# APPLICATION SPECIFIC CONFIGURATION
applications:
  - name: registry
    <<: *defaults
    routes:
      - route: https://registry-cx-editorial.apps.backbasepcf.com
    path: ../../apps/registry.war
  - name: gateway
    <<: *defaults
    routes:
      - route: https://gateway-cx-editorial.apps.backbasepcf.com
    path: ../../apps/gateway.war
    health-check-http-endpoint: /api_gw/health
    env:
      GATEWAY_LOAD-BALANCER-HEALTH-CHECK: false
      MANAGEMENT_SECURITY_ENABLED: false
  - name: auth
    <<: *defaults
    no-route: true
    path: ../../apps/auth.war
    env:
      MANAGEMENT_SECURITY_ENABLED: false
      SPRING_ACTIVEMQ_BROKER_URL: tcp://10.210.4.179:51616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
      USERCTX_KEY: JWTSecretKeyDontUseInProduction!
      SSO_JWT_EXTERNAL_EXPIRATION: 3600
      SSO_JWT_EXTERNAL_RENEW: 1800
      SSO_JWT_EXTERNAL_NOT-VALID-AFTER: 86400
```

## What you expected to occur

With cf version 6.36.1+e3799ad7e.2018-04-04, properties are properly set up as user environment variables

## CLI Version

6.37.0+a40009753.2018-05-25

## CC API Endpoint Version

api version:    2.94.0

## Platform & Shell Details

Mac OS X 10.13.4 iTerm and also Windows with PowerShell

## Any other relevant information

All works properly with 6.36.2

**Comment by XenoPhex** [comment]
@torrespro I believe there may be misunderstanding how YAML anchors/aliases work.

According to the YAML standard, when using anchors with the append (`<<`) tag, the parser just copies all the values defined by the anchor (the `&`) into the value you're appending it to. Given this information, your YAML example equates to this:
```YAML
---
applications:
  - name: registry
    instances: 1
    memory: 1GB
    disk_quota: 300M
    health-check-type: http
    health-check-http-endpoint: /health
    buildpack: https://github.com/cloudfoundry/java-buildpack.git
    env:
      eureka.client.serviceUrl.defaultZone: https://registry-cx-editorial.apps.backbasepcf.com/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      EUREKA_INSTANCE_HOSTNAME: $CF_INSTANCE_INTERNAL_IP
      EUREKA_INSTANCE_NON_SECURE_PORT: 8080
      SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
      EXTERNAL_SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
      EXTERNAL_ENC_SECRET_KEY: JWTEncKeyDontUseInProduction666!
      LOGGING_SECURED_ENABLED: false
      JBP_CONFIG_DEBUG: '{enabled: true}'
      BACKBASE_ENVROLE: editorial
    routes:
      - route: https://registry-cx-editorial.apps.backbasepcf.com
    path: ../../apps/registry.war
  - name: gateway
    instances: 1
    memory: 1GB
    disk_quota: 300M
    health-check-type: http
    health-check-http-endpoint: /health
    buildpack: https://github.com/cloudfoundry/java-buildpack.git
    env:
      eureka.client.serviceUrl.defaultZone: https://registry-cx-editorial.apps.backbasepcf.com/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      EUREKA_INSTANCE_HOSTNAME: $CF_INSTANCE_INTERNAL_IP
      EUREKA_INSTANCE_NON_SECURE_PORT: 8080
      SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
      EXTERNAL_SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
      EXTERNAL_ENC_SECRET_KEY: JWTEncKeyDontUseInProduction666!
      LOGGING_SECURED_ENABLED: false
      JBP_CONFIG_DEBUG: '{enabled: true}'
      BACKBASE_ENVROLE: editorial
    routes:
      - route: https://gateway-cx-editorial.apps.backbasepcf.com
    path: ../../apps/gateway.war
    health-check-http-endpoint: /api_gw/health
    env:
      GATEWAY_LOAD-BALANCER-HEALTH-CHECK: false
      MANAGEMENT_SECURITY_ENABLED: false
  - name: auth
    instances: 1
    memory: 1GB
    disk_quota: 300M
    health-check-type: http
    health-check-http-endpoint: /health
    buildpack: https://github.com/cloudfoundry/java-buildpack.git
    env:
      eureka.client.serviceUrl.defaultZone: https://registry-cx-editorial.apps.backbasepcf.com/eureka
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: true
      EUREKA_INSTANCE_HOSTNAME: $CF_INSTANCE_INTERNAL_IP
      EUREKA_INSTANCE_NON_SECURE_PORT: 8080
      SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
      EXTERNAL_SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
      EXTERNAL_ENC_SECRET_KEY: JWTEncKeyDontUseInProduction666!
      LOGGING_SECURED_ENABLED: false
      JBP_CONFIG_DEBUG: '{enabled: true}'
      BACKBASE_ENVROLE: editorial
    no-route: true
    path: ../../apps/auth.war
    env:
      MANAGEMENT_SECURITY_ENABLED: false
      SPRING_ACTIVEMQ_BROKER_URL: tcp://10.210.4.179:51616
      SPRING_ACTIVEMQ_USER: admin
      SPRING_ACTIVEMQ_PASSWORD: admin
      USERCTX_KEY: JWTSecretKeyDontUseInProduction!
      SSO_JWT_EXTERNAL_EXPIRATION: 3600
      SSO_JWT_EXTERNAL_RENEW: 1800
      SSO_JWT_EXTERNAL_NOT-VALID-AFTER: 86400
```
Looking at the `gateway` and `auth` apps, we see that the `env` tag is listed twice, in these cases the YAML standard says that the last one wins.

## Why did this work before and not now?
We've recently upgraded the YAML library the CF CLI uses and it appears to be more strict (aka follows the standard more closely).

## What do should you do now?
Move all your env vars into a new top level anchor and append that into the individual `env` tags. 
**Note**: Avoid calling the new anchor `env`, as `env` is a deprecated top level value. We'd recommend calling the new anchor something else or you'll see a lot of crazy deprecation warnings/errors.
