### ISSUE TITLE
Default values for variable substitution

### ISSUE THREAD

**Issue by ihrigb** [cloudfoundry/cli#1514]
**Please provide details on the following items. Failure to do so may result in deletion of your feature request.**

For variable substitution, we could use default values. Variable files would of course overwrite them. Notation could be after a separator, like a colon:

**What's the user value of this feature request?**
Manifests can provide default values, which can be overwritten by specific var files for e.g. certain environments.

**Who is the functionality for?**
Anyone deploying applications with manifests could use this feature.

**How often will this functionality be used by the user?**
With each deployment, if functionality is used.

**Who else is affected by the change?**
CLI, Doc

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
`((<variable>[:<defaltValue>]))`

Example from docs:
```yaml
---
applications:
- name: test-app
  instances: ((instances:1))
  memory: ((memory:2G))
  buildpack: go_buildpack
  env:
    GOPACKAGENAME: go_calls_ruby
  command: go_calls_ruby
```

**Describe alternatives you've considered**
Specifying each variable in each var file, although there is a common default.

**Additional context**
n/a
