### ISSUE TITLE
exec: "git": executable file not found in %PATH% windows stack

### ISSUE THREAD

**Issue by cs4242** [cloudfoundry/cli#1864]
Tried to push a simple nodejs & python app, 
and got the following error:

> Waiting for API to complete processing files...
> 
> Stopping app...
> 
> Staging app and tracing logs...
>    Cell b98c5e49-291b-46ce-9d30-0f26e504fdf7 creating container for instance c7aca7dc-c018-4ae2-9e35-52dd085de038
>    Cell b98c5e49-291b-46ce-9d30-0f26e504fdf7 successfully created container for instance c7aca7dc-c018-4ae2-9e35-52dd085de038
>    Downloading app package...
>    Downloaded app package (8.1M)
>    exec: "git": executable file not found in %PATH%
>    Exit status 1
>    Cell b98c5e49-291b-46ce-9d30-0f26e504fdf7 destroying container for instance c7aca7dc-c018-4ae2-9e35-52dd085de038
>    Cell b98c5e49-291b-46ce-9d30-0f26e504fdf7 stopping instance c7aca7dc-c018-4ae2-9e35-52dd085de038
>    Cell b98c5e49-291b-46ce-9d30-0f26e504fdf7 successfully destroyed container for instance c7aca7dc-c018-4ae2-9e35-52dd085de038
> Error staging application: Staging error: staging failed
> FAILED

i believe this is happening because i am running with a windows stack.
here is my manifest file:

```
---
applications:
  - name: bsodTest
    memory: 2GB
    disk_quota: 2GB
    instances: 1
    command: node app.js
    stack: windows2012R2
    buildpacks:
      - https://github.com/cloudfoundry/python-buildpack
      - https://github.com/cloudfoundry/nodejs-buildpack.git
```
