### ISSUE TITLE
Processes cannot be removed from application

### ISSUE THREAD

**Issue by benschoch** [cloudfoundry/cli#1924]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [x] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.
- [x] If this is an issue for the v7 beta release, I've read through the [official docs](https://docs.cloudfoundry.org/cf-cli/v7.html) and the [release notes](https://github.com/cloudfoundry/cli/releases).

**Describe the bug and the command you saw an issue with**
I pushed an app with a manifest file that includes multiple processes for background tasks:
```
---
applications:
  - name: ...
    ...
    processes:
      ...
      - type: cron
        command: ...
        disk_quota: 1G
        health-check-type: process
        instances: 1
        memory: 56M
        timeout: 10
```
I pushed via default `cf push` (and also tried with `cf v3-push`) and applied the manifest file via `cf v3-apply-manifest`.

**What happened**
Unfortunately it seems like re-applying the manifest file with adaptions to the process `type` leads to additional processes being started without removing the old ones. I was unable to remove the processes via API as well. I reduced the number of instances to 0 but that just leads to an instant restart of the instance.

**Expected behavior**
Processes that are not defined in the manifest file anymore are removed automatically on a new push. Alternatively a removal of processes should be possible via API.

**To Reproduce**
Steps to reproduce the behavior; include the exact CLI commands and verbose output:
1. Run `cf push`
2. Run `cf v3-apply-manifest manifest-file.yml`
3. Modify the `type` of the processes defined in the manifest file
4. Run `cf v3-apply-manifest manifest-file.yml`
5. Use `cf app` to see all processes including the "old" ones are running.

**Provide more context**
- Mac OS X 10.14 iTerm
- CF Version 6.46.1
- API Version 2.142.0
