### ISSUE TITLE
cf v3-apply-manifest  -invalid request body

### ISSUE THREAD

**Issue by dcuenot** [cloudfoundry/cli#1926]
**Please fill out the issue checklist below and provide ALL the requested information.**

- [x] I reviewed open and closed github issues that may be related to my problem.
- [x] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [ ] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [x] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
When I try to upload this `manifest.yml`, with this command: `cf v3-apply-manifest`, I get this error from the API: `Request invalid due to parse error: invalid request body`

```
---
applications:
    - name: my-app
      env:
          USERNAME: username
          CLIENT_SECRET: ':test'
      buildpacks:
          - https://github.com/cloudfoundry/python-buildpack
      processes:
          - type: worker
            instances: 1
            memory: 1024M
            command: python -m src
            health-check-type: process
```

This issue is related to the colon at the beginning of `CLIENT_SECRET`.
If I remove it, `cf v3-apply-manifest` is working.

**Workaround with surprising answer**
I found a workaround in two steps:
1. Apply the `manifest.yml` without the `CLIENT_SECRET`
```
---
applications:
    - name: my-app
      env:
          USERNAME: username
      buildpacks:
          - https://github.com/cloudfoundry/python-buildpack
      processes:
          - type: worker
            instances: 1
            memory: 1024M
            command: python -m src
            health-check-type: process
```

2. Use set-env to define the variables: `cf v3-set-env my-app CLIENT_SECRET ':test'`

With these two commands, it's working 🙂
When I run the command to generate the manifest:
`cf curl /v3/apps/cfbb2bd8-a9b0-4a80-bcee-25b34768000a/manifest`, the `CLIENT_SECRET` is perfect.

```API answer
---
applications:
- name: my-app
  env:
    CLIENT_SECRET: ":test"
    USERNAME: tu-billing
  buildpacks:
  - https://github.com/cloudfoundry/python-buildpack
  stack: cflinuxfs3
  processes:
  - type: web
    instances: 1
    memory: 1024M
    disk_quota: 1024M
    health-check-type: port
  - type: worker
    instances: 1
    memory: 1024M
    disk_quota: 1024M
    command: python -m src
    health-check-type: process
```

And of course, if I try to apply the manifest I got with the API, the `cf v3-apply-manifest` is failing 😟

**Provide more context**
- platform and shell details: Mac OS X 10.11 iTerm zsh
- version of the CLI: cf version 6.51.0+2acd15650.2020-04-07
