### ISSUE TITLE
cf v7 push strips commas from environment variables

### ISSUE THREAD

**Issue by christianerbsmehl** [cloudfoundry/cli#2172]
- [X] I reviewed open and closed github issues that may be related to my problem.
- [X] I tried updating to the latest version of the CF CLI to see if it fixed my problem.
- [X] I attempted to run the command with `CF_TRACE=1` to help debug the issue.
- [X] I am reporting a bug that others will be able to reproduce.

**Describe the bug and the command you saw an issue with**
When pushing an app with an environment variable (defined in the manifest) containing commas, those are stripped on push.
This happens only when using cf cli v7.

Example manifest:
```yaml
---
applications:
  - name: "comma-sample"
    memory: "128M"
    disk_quota: "128M"
    instances: 1
    buildpacks:
      - staticfile_buildpack
    stack: "cflinuxfs3"
    path: "."
    random-route: true
    env:
      SPECIAL_IDS: "1234,5678,1337"
```

**What happened**
The value of the env variable is modified. All commas are removed. E.g. `1234,5678,1337` becomes `123456781337`

**Expected behavior**
The env variable should not be modified on push.

**Exact Steps To Reproduce**
1. Run `cf7 push -f manifest.yml` (e.g. from example above)
2. Get env vars `cf7 env comma-sample`
3. Reveal section `User-Provided`
4. Swear because value of env variable is `123456781337` 😉 

**Provide more context**
- Windows 10 1909 w/ Windows Terminal/PowerShell/Git bash
- cf7.exe version 7.2.0+be4a5ce2b.2020-12-10 (Issue exists)
- cf.exe version 6.45.0+5f9ff16f9.2019-06-03 (No issue)
- cf 2.10.13 (Tanzu) / API 3.85.0

Side notes: 

- same issue with cf push --strategy rolling with cli v7
- cf push with cli v6 works as expected
- cf set-env with cli v7 works as expected
- no issue when using semicolon as separator char
