### ISSUE TITLE
Allow encrypting secret environment variables in a manifest

### ISSUE THREAD

**Issue by tjarratt** [cloudfoundry/cli#310]
I have an application which needs to cryptographically sign some resources (ala Codesigning for an iOS app) and it feels like the best way to deploy this as part of my app is to

* create a private key with a password
* check in the private key into my app's repo
* set the password as an environment variable (in my manifest, or after I deploy)

However, currently that password is in plaintext and anyone could read it. It would be best if I could encrypt the value, store it in a manifest, and then decrypt it on my instance (at or before runtime). Travis-CI supports a similar concept with their ["secure" environment variables](http://docs.travis-ci.com/user/environment-variables/#Secure-Variables). 

Something like this would be great:

```yml
---
applications:
  name: SUPER-SECRET-APP
  secure-env:
     - "ENCRYPTED-KEY-VALUE-STUFF-GOES-HERE"
```
