### ISSUE TITLE
create-app-manifest only includes one host

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cli#414]
This is using version 6.11.0-bba7fcf-2015-04-14T00:39:29+00:00

If I have an application with multiple hostnames, such as one created from this manifest:

```yml
---
applications:
  - name: myapp
    memory: 64M
    hosts:
      - multi-samp-one
      - multi-samp-two
    buildpack: https://github.com/cloudfoundry-community/staticfile-buildpack.git
```

Running `cf create-app-manifest myapp` produces this manifest:

```yml
---
applications:
- name: myapp
  memory: 64M
  instances: 1
  host: multi-samp-one
  domain: cfapps.io
```

Which only includes the first host, and ignores "multi-samp-two".
