### ISSUE TITLE
Manifest inheritance of applications with the same name

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry/cli#479]
(Moving this from #434 to have the intended conversation)

I am running into an issue with manifest inheritance where if I have the app specified in the main manifest and try to override it from the child one, two apps are created.

It is reproduced with [this test](https://gist.github.com/dlapiduz/5eff17e54f82ae20d628) but I am not sure if this is an issue that we should solve at the merging level.

If two apps have the same name I expect them to be merged, is that not the desired behavior?

Some manifest examples:

```
---
# main.yml
memory: 512M
services:
- mydb
applications:
- name: myapp
  path: .
```

```
---
# dev.yml
inherit: main.yml
applications:
- name: myapp
  host: myapp-dev
```

And the merged result is something like:
```
memory: 512M
services:
- mydb
applications:
- name: myapp
  path: .
- name: myapp
  host: myapp-dev
```

When I was expecting:
```
memory: 512M
services:
- mydb
applications:
- name: myapp
  path: .
  host: myapp-dev
```
