### ISSUE TITLE
Allow service creation via manifest

### ISSUE THREAD

**Issue by tsaleh** [cloudfoundry/cli#491]
It'd be helpful to be able to have the cf cli be able to create services based on information in the manifest.  Since services like rabbitmq are often shared among various applications, this should be a global section.

This is separate from the `services:` section under each `application`, though those will likely reference the services in this global section.

#### Manifest changes:

```
---
services:
  - service: redis
    name: cache
    plan: 100
  - service: rabbitmq
    name: queue
    plan: 100 
```

#### CLI changes:

```
$ cf create-services-from-manifest
Creating redis service instance "cache", plan: 100
Creating rabbitmq service instance "queue", plan: 100
```

If some exist:

```
$ cf create-services-from-manifest
redis service instance "cache", plan: 100 exists
Creating rabbitmq service instance "queue", plan: 100
```

if they don't match the manifest:

```
$ cf create-services-from-manifest
service named "cache" exists as redis service instance, plan: 200.  Mismatch detected, failing.
```

(note that it doesn't attempt to create the other services in this scenario)
