### ISSUE TITLE
running 'cf push' and specifying an app should allow command line flags

### ISSUE THREAD

**Issue by MrEnzyme** [cloudfoundry/cli#586]
If I'm running cf push on a single app from a manifest I should be able to give options like --no-route or -n for hostname. Currently it gives the error "Incorrect Usage. Command line flags (except -f) cannot be applied when pushing multiple apps from a manifest file."

**Comment by camelpunch** [comment]
@MrEnzyme can you provide us with an example manifest.yml for this?

**Comment by MrEnzyme** [comment]
any manifest with multiple apps, for example:
```
---
memory: 64M
instances: 1
applications:
- name: grafana
  host: grafana
  buildpack: https://github.com/cloudfoundry-community/staticfile-buildpack.git
  path: ./grafana
- name: graphite-api
  memory: 1024M
  host: graphite-api
  buildpack: https://github.com/cloudfoundry/python-buildpack.git
  path: ./graphite-api
  env:
    GRAPHITE_API_CONFIG: config.yaml
```
What I'd like to be able to do is something like ```cf-push grafana --no-route -n custom-hostname``` and just use any command line flags given that i'm only pushing one app, and have it override whatever the relevant manifest config is.
