### ISSUE TITLE
Breaking changes to manifest format for services

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/cli#71]
I used to be able to specify services to create (as well as bind) in a manifest, e.g. 

```
  services:
    mysql:
      label: cleardb
      provider: cleardb
      plan: spark
    rabbit:
      label: cloudamqp
      provider: cloudamqp
      plan: lemur
    redis:
      label: rediscloud
      provider: garantiadata
      plan: 20mb
```

Now I just get 

```
$ CF_TRACE=true cf push
FAILED
Error reading manifest file:
Expected services to be a list of strings.
```
